name: wait-for-checks
on:
  workflow_dispatch:
  push:
    branches:
      - wait-for-checks-NOPE

jobs:
  sleep:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 10
      - run: sleep 10
      - run: sleep 10
  check-commit-message:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 30
      - if: contains(github.event.head_commit.message, 'FAIL')
        run: exit 1
